
    create table Player (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        position integer,
        realWorldTeam_id bigint,
        team_id bigint,
        primary key (id)
    )

    create table RealWorldTeam (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        primary key (id)
    )

    create table Team (
        id bigint generated by default as identity (start with 1),
        logoUrl varchar(255),
        name varchar(255),
        primary key (id)
    )

    alter table Player 
        add constraint FK_dfb32sf590knl1mfmukt3j46b 
        foreign key (realWorldTeam_id) 
        references RealWorldTeam

    alter table Player 
        add constraint FK_2w0ldfd2ytqf3gkh4q436fw5i 
        foreign key (team_id) 
        references Team
