
    create table Match (
        id bigint generated by default as identity (start with 1),
        awayTeam_id bigint,
        homeTeam_id bigint,
        stage_id bigint,
        primary key (id)
    )

    create table Player (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        position integer,
        realWorldTeam_id bigint,
        team_id bigint,
        primary key (id)
    )

    create table RealWorldTeam (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        primary key (id)
    )

    create table Stage (
        id bigint generated by default as identity (start with 1),
        date timestamp,
        primary key (id)
    )

    create table Stage_goals (
        Stage_id bigint not null,
        goals integer,
        player_id bigint not null,
        primary key (Stage_id, player_id)
    )

    create table Team (
        id bigint generated by default as identity (start with 1),
        logoUrl varchar(255),
        name varchar(255),
        primary key (id)
    )

    alter table Match 
        add constraint FK_8oa53tubddswpw1xfjhkltoex 
        foreign key (awayTeam_id) 
        references Team

    alter table Match 
        add constraint FK_us9aayhm4hu9ay1infx52o2r 
        foreign key (homeTeam_id) 
        references Team

    alter table Match 
        add constraint FK_9hy45ei9b9i3qan061l0brvb3 
        foreign key (stage_id) 
        references Stage

    alter table Player 
        add constraint FK_dfb32sf590knl1mfmukt3j46b 
        foreign key (realWorldTeam_id) 
        references RealWorldTeam

    alter table Player 
        add constraint FK_2w0ldfd2ytqf3gkh4q436fw5i 
        foreign key (team_id) 
        references Team

    alter table Stage_goals 
        add constraint FK_q0f8pha182s55xefdvvuvtwtt 
        foreign key (player_id) 
        references Player

    alter table Stage_goals 
        add constraint FK_m0r3u9enns7ocu49qsn7tfhig 
        foreign key (Stage_id) 
        references Stage
