
    create table Player (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        position integer,
        realWorldTeam_id bigint,
        primary key (id)
    )

    create table RealWorldTeam (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        primary key (id)
    )

    alter table Player 
        add constraint FK_dfb32sf590knl1mfmukt3j46b 
        foreign key (realWorldTeam_id) 
        references RealWorldTeam
